name: Go

on:
  push:
    branches: [ "develop" ]

env:
  IMAGE_NAME: money-liff
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Make env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_APP_ENV: ${{ github.ref_name }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
        envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Show env file
      run: cat .env

    - name: Build image
      run: docker build -t tonyzhuo/$IMAGE_NAME:$RELEASE_VERSION .

    - name: Save docker image as tar file
      run: docker save tonyzhuo/$IMAGE_NAME:$RELEASE_VERSION > liff.tar

    - name: Upload tar file to github artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-artifact
        path: liff.tar

  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -cover -v ./...

  push-image-to-docker-hub:
    name: Push image to docker hub
    needs: [ build-image, tests ]
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact

      - name: Load out docker image
        run: docker load < liff.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image to Docker Hub
        run: docker push tonyzhuo/$IMAGE_NAME:$RELEASE_VERSION